version: '3.0'
services:
  smart_contract:
    image: hyperledger/fabric-tools:2.5
    volumes:
      - ./:/root/sig_graph
      - ./dev/test-network:/opt/fabric
    working_dir: /root/sig_graph
    command: sleep infinity
    network_mode: host
    environment:
      - FABRIC_HOME=/opt/fabric

  golang:
    image: golang:1.20.6-bullseye
    volumes:
      - ./:/root/sig_graph
      - ./dev/test-network:/opt/fabric
    working_dir: /root/sig_graph
    command: sleep infinity
    network_mode: host
    environment:
      - FABRIC_HOME=/opt/fabric