version: '3.0'
services:
  smart_contract:
    image: golang:1.20.2
    volumes:
      - ./:/root/sig_graph
    working_dir: /root/sig_graph
    command: sleep infinity
    network_mode: host
    environment:
      - FABRIC_HOME=/opt/fabric